/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bankEnterprise;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import main.signUp;

/**
 *
 * @author Team NYAM
 */
public class financialLogin extends javax.swing.JFrame {

    /**
     * Creates new form financialLogin
     */
    public financialLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelFinanceTitle = new javax.swing.JLabel();
        jLabelLOGOfinance = new javax.swing.JLabel();
        jLabelLogo2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnUsername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnPassword = new javax.swing.JTextField();
        selectUniRole = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();
        jButtonBackUniLogin = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabelFinanceTitle.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabelFinanceTitle.setText("FINANCIAL LOGIN");
        jPanel1.add(jLabelFinanceTitle);
        jLabelFinanceTitle.setBounds(550, 450, 230, 50);

        jLabelLOGOfinance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/northeastern-university-student-financial-services-2-removebg-preview.png"))); // NOI18N
        jPanel1.add(jLabelLOGOfinance);
        jLabelLOGOfinance.setBounds(510, 320, 290, 135);

        jLabelLogo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/northeasternuniversity_logoseal-2.png"))); // NOI18N
        jPanel1.add(jLabelLogo2);
        jLabelLogo2.setBounds(600, 240, 95, 135);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("USERNAME:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(531, 510, 84, 17);

        btnUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsernameActionPerformed(evt);
            }
        });
        jPanel1.add(btnUsername);
        btnUsername.setBounds(640, 510, 160, 23);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("PASSWORD:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(532, 550, 90, 17);
        jPanel1.add(btnPassword);
        btnPassword.setBounds(640, 550, 160, 23);

        selectUniRole.setForeground(new java.awt.Color(255, 255, 255));
        selectUniRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bank Employee", "Bank Admin" }));
        jPanel1.add(selectUniRole);
        selectUniRole.setBounds(640, 590, 160, 23);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("ROLE:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(540, 590, 50, 17);

        loginBtn.setBackground(new java.awt.Color(0, 0, 0));
        loginBtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginBtn.setText("LOGIN");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        jPanel1.add(loginBtn);
        loginBtn.setBounds(600, 650, 110, 30);

        jButtonBackUniLogin.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonBackUniLogin.setText("BACK");
        jButtonBackUniLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackUniLoginActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBackUniLogin);
        jButtonBackUniLogin.setBounds(20, 20, 72, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/finance 1.jpeg"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(-390, 0, 2000, 990);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1606, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 943, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUsernameActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
        
        String role = selectUniRole.getSelectedItem().toString();
        String username = btnUsername.getText();
        String password = btnPassword.getText();
        
        if (username.isEmpty() || password.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please enter details correctly");
        return;
        }
        
        if(role.equals("Bank Employee")){
         try{
            java.sql.Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/universitysystem", "root", "Masters@23");
            java.sql.Statement statement = connection.createStatement();
            String studentQuery = "SELECT * FROM universitysystem.bankemployee WHERE username = '"+username+"' and password = '"+password+"'";
            java.sql.ResultSet studentData = statement.executeQuery(studentQuery);
            if(!studentData.next()){
                JOptionPane.showMessageDialog(null,"Invalid Credentials");
            }
                
//            while(studentData.next()){
            else{
                //String studName = studentData.getString("Name"); 
                String studName = studentData.getString("Name"); 
                String name = capitalizeFirstLetter(studentData.getString("Name"));
                JOptionPane.showMessageDialog(null, "Welcome, " + name + "!");
                bankAction emp = new bankAction();
                emp.setName(studName);
                setVisible(false);
                emp.setVisible(true);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }   
        }else if(role.equals("Bank Admin")){
            if(username.equals("BANADMIN") && password.equals("7890")){
                 JOptionPane.showMessageDialog(null, "Welcome Admin");
                bankAdmin bakAdminObj = new bankAdmin();
                setVisible(false);
                bakAdminObj.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null,"Invalid Credentials");
            }
        }else{
            JOptionPane.showMessageDialog(null,"Please Enter Details Properly");
        }
        
    }//GEN-LAST:event_loginBtnActionPerformed
 private String capitalizeFirstLetter(String original) {
    if (original == null || original.length() == 0) {
        return original;
    }
    return original.substring(0, 1).toUpperCase() + original.substring(1).toLowerCase();
}
    private void jButtonBackUniLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackUniLoginActionPerformed
        // TODO add your handling code here:
        signUp signUpObj = new signUp();
        setVisible(false);
        signUpObj.setVisible(true);
    }//GEN-LAST:event_jButtonBackUniLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(financialLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(financialLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(financialLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(financialLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new financialLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField btnPassword;
    private javax.swing.JTextField btnUsername;
    private javax.swing.JButton jButtonBackUniLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelFinanceTitle;
    private javax.swing.JLabel jLabelLOGOfinance;
    private javax.swing.JLabel jLabelLogo2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginBtn;
    private javax.swing.JComboBox<String> selectUniRole;
    // End of variables declaration//GEN-END:variables
}
