/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package university;

import java.sql.DriverManager;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import main.signUp;

/**
 *
 * @author Team NYAM
 */
public class uniLogin extends javax.swing.JFrame {

    /**
     * Creates new form uniLogin
     */
    public uniLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonBackUniLogin = new javax.swing.JButton();
        jLabelLogoUNILogin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnUsername = new javax.swing.JTextField();
        btnPassword = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        selectUniRole = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabelTitlelogin = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonBackUniLogin.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonBackUniLogin.setText("BACK");
        jButtonBackUniLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackUniLoginActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBackUniLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 21, -1, -1));

        jLabelLogoUNILogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Northeastern_University_Logo-White.png"))); // NOI18N
        jPanel1.add(jLabelLogoUNILogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, 350, 140));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("USERNAME:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 400, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("PASSWORD:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 450, -1, -1));

        btnUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsernameActionPerformed(evt);
            }
        });
        jPanel1.add(btnUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 400, 160, -1));

        btnPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(btnPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 450, 160, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("ROLE:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 500, -1, -1));

        selectUniRole.setForeground(new java.awt.Color(255, 255, 255));
        selectUniRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student", "Professor", "University Admin" }));
        jPanel1.add(selectUniRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 500, 160, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("LOGIN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 560, 110, 30));

        jLabelTitlelogin.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabelTitlelogin.setText("UNIVERSITY LOGIN");
        jPanel1.add(jLabelTitlelogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 300, 240, 70));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/main landing.jpeg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1470, 1020));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String role = selectUniRole.getSelectedItem().toString();
        String username = btnUsername.getText();
        String password = btnPassword.getText();
        
        if (username.isEmpty() || password.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please enter details correctly");
        return;
    }
        

        if(role.equals("Student")){
         try{
            java.sql.Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/universitysystem", "root", "Masters@23");
            java.sql.Statement statement = connection.createStatement();
            String studentQuery = "SELECT * FROM universitysystem.students WHERE username = '"+username+"' and password = '"+password+"'";
            java.sql.ResultSet studentData = statement.executeQuery(studentQuery);
            if(!studentData.next()){
                JOptionPane.showMessageDialog(null,"Invalid Credentials");
            }
                
//            while(studentData.next()){
                else {
                String studName = studentData.getString("Name"); 
                String name = capitalizeFirstLetter(studentData.getString("Name"));// Assuming column name is 'Name'
                JOptionPane.showMessageDialog(null, "Welcome, " + name + "!");
                student stud = new student();
                stud.setName(studName, username);
                setVisible(false);
                stud.setVisible(true);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }   
        }else if(role.equals("Professor")){
            try{
            java.sql.Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/universitysystem", "root", "Masters@23");
            java.sql.Statement statement = connection.createStatement();
            String profQuery = "SELECT * FROM universitysystem.professors WHERE username = '"+username+"' and password = '"+password+"'";
            java.sql.ResultSet profData = statement.executeQuery(profQuery);

            if(!profData.next()){
                JOptionPane.showMessageDialog(null,"Invalid Credentials");
            }
            
//            while(profData.next()){
            else{
                
                String profName = capitalizeFirstLetter(profData.getString("Name")); // Assuming 'Name' is the column name
                JOptionPane.showMessageDialog(null, "Welcome, Professor " + profName + "!");

                String currentSubjectTeach = profData.getString("subjectTeach");
                professor profObj = new professor();
                profObj.setProfData(username, currentSubjectTeach);
                setVisible(false);
                profObj.setVisible(true);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        }else if(role.equals("University Admin")){
            if(username.equals("UNIADMIN") && password.equals("7890")){
                 JOptionPane.showMessageDialog(null, "Welcome Admin");
                staffAdmin staffAdminObj = new staffAdmin();
                setVisible(false);
                staffAdminObj.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null,"Invalid Credentials");
            }
        }else{
            JOptionPane.showMessageDialog(null,"Please Enter Details Properly");
        }


//String role = selectUniRole.getSelectedItem().toString();
//    String username = btnUsername.getText();
//    String password = btnPassword.getText();
//
//    if (username.isEmpty() || password.isEmpty()) {
//        JOptionPane.showMessageDialog(null, "Please enter both username and password");
//        return;
//    }
//
//    if(role.equals("Student")){
//        validateUser("students", username, password);
//    } else if(role.equals("Professor")){
//        validateUser("professors", username, password);
//    } else if(role.equals("University Admin")){
//        validateAdmin(username, password);
//    } else {
//        JOptionPane.showMessageDialog(null, "Please select a valid role");
//    }
//}
//
//private void validateUser(String tableName, String username, String password) {
//    String query = "SELECT * FROM universitysystem." + tableName + " WHERE username = ? and password = ?";
//    try (java.sql.Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/universitysystem", "root", "Masters@23");
//         java.sql.Statement statement = connection.prepareStatement(query)) {
//        
//        String studentQuery = "SELECT * FROM universitysystem.students WHERE username = '"+username+"' and password = '"+password+"'";
//            java.sql.ResultSet userData = statement.executeQuery(studentQuery);
//
//        if (!userData.next()) {
//            JOptionPane.showMessageDialog(null, "Invalid Credentials");
//        } else {
//
//            String name = capitalizeFirstLetter(userData.getString("Name"));// Assuming column name is 'Name'
//            JOptionPane.showMessageDialog(null, "Welcome, " + name + "!");
//            
//            if (tableName.equals("students")) {
//                student stud = new student();
//                stud.setName(name, username);
//                setVisible(false);
//                stud.setVisible(true);
//            } 
////            else if (tableName.equals("professors")) {
////                
////                
////                String profQuery = "SELECT * FROM universitysystem.professors WHERE username = '"+username+"' and password = '"+password+"'";
////                java.sql.ResultSet profData = statement.executeQuery(profQuery);
////                String subject = profData.getString("subjectTeach"); // Assuming column name is 'subjectTeach'
////                professor profObj = new professor();
////                profObj.setProfData(username, subject);
////                setVisible(false);
////                profObj.setVisible(true);
////            }
//
//
//
//    else if(tableName.equals("Professor")){
//    try{
//        java.sql.Connection connection2 = DriverManager.getConnection("jdbc:mysql://localhost:3306/universitysystem", "root", "Masters@23");
//        String profQuery = "SELECT * FROM universitysystem.professors WHERE username = '"+username+"' and password = '"+password+"'";
//        
//        
//        java.sql.Statement statement2 = connection2.prepareStatement(profQuery);
//        
//    
//            java.sql.ResultSet profData = statement2.executeQuery(profQuery);
//        if(!profData.next()){
//            JOptionPane.showMessageDialog(null,"Invalid Credentials");
//        } else {
//            String profName = capitalizeFirstLetter(profData.getString("Name")); // Assuming 'Name' is the column name
//            JOptionPane.showMessageDialog(null, "Welcome, Professor " + profName + "!");
//            
//            String currentSubjectTeach = profData.getString("subjectTeach"); // Assuming 'subjectTeach' is the column name
//            professor profObj = new professor();
//            profObj.setProfData(username, currentSubjectTeach);
//            setVisible(false);
//            profObj.setVisible(true);
//        }
//    } catch(Exception e){
//        JOptionPane.showMessageDialog(null,e);
//    } finally {
//        if (statement != null) {
//            statement.close();
//        }
//        if (connection != null) {
//            connection.close();
//        }
//    }
//}
//
//        }
//    } catch (Exception e) {
//        JOptionPane.showMessageDialog(null, e);
//    }
//    
//}
//

//private void validateAdmin(String username, String password) {
//    if (username.equals("UNIADMIN") && password.equals("7890")) {
//        JOptionPane.showMessageDialog(null, "Welcome Admin");
//        staffAdmin staffAdminObj = new staffAdmin();
//        setVisible(false);
//        staffAdminObj.setVisible(true);
//    } else {
//        JOptionPane.showMessageDialog(null, "Invalid Credentials");
//    }




    }//GEN-LAST:event_jButton1ActionPerformed

    private String capitalizeFirstLetter(String original) {
    if (original == null || original.length() == 0) {
        return original;
    }
    return original.substring(0, 1).toUpperCase() + original.substring(1).toLowerCase();
}
    private void jButtonBackUniLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackUniLoginActionPerformed
        // TODO add your handling code here:
        signUp signUpObj = new signUp();
        setVisible(false);
        signUpObj.setVisible(true);
    }//GEN-LAST:event_jButtonBackUniLoginActionPerformed

    private void btnUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUsernameActionPerformed

    private void btnPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(uniLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(uniLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(uniLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(uniLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new uniLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField btnPassword;
    private javax.swing.JTextField btnUsername;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonBackUniLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelLogoUNILogin;
    private javax.swing.JLabel jLabelTitlelogin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> selectUniRole;
    // End of variables declaration//GEN-END:variables
}
