/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package emergencyEnterprise;

import java.sql.DriverManager;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import emergencyEnterprise.emergency.Model.crimereport;
import university.student;
import university.uniLogin;


/**
 *
 * @author Team NYAM
 */
public class crimeReport extends javax.swing.JFrame {

    /**
     * Creates new form crimeReport
     */
    public crimeReport() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        rcname = new javax.swing.JLabel();
        rcphone = new javax.swing.JLabel();
        rcaddress = new javax.swing.JLabel();
        rccrimedetails = new javax.swing.JLabel();
        rcnameTxt = new javax.swing.JTextField();
        rcphoneTxt = new javax.swing.JTextField();
        rcaddressTxt = new javax.swing.JTextField();
        rccdTxt = new javax.swing.JTextField();
        rcsubmitBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        detailsTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        viewBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnStudLogout1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(128, 185, 229));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rcname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        rcname.setText("NAME:");
        jPanel1.add(rcname, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 370, -1, -1));

        rcphone.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        rcphone.setText("PHONE:");
        jPanel1.add(rcphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 410, -1, -1));

        rcaddress.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        rcaddress.setText("ADDRESS:");
        jPanel1.add(rcaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 450, -1, -1));

        rccrimedetails.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        rccrimedetails.setText("CRIME DETAILS:");
        jPanel1.add(rccrimedetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 490, -1, -1));

        rcnameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rcrcnameTxtActionPerformed(evt);
            }
        });
        jPanel1.add(rcnameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 370, 188, -1));

        rcphoneTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rcrcphoneTxtActionPerformed(evt);
            }
        });
        jPanel1.add(rcphoneTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 410, 188, -1));
        jPanel1.add(rcaddressTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 450, 188, -1));
        jPanel1.add(rccdTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 490, 188, -1));

        rcsubmitBtn.setBackground(new java.awt.Color(0, 0, 0));
        rcsubmitBtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        rcsubmitBtn.setForeground(new java.awt.Color(255, 255, 255));
        rcsubmitBtn.setText("SUBMIT");
        rcsubmitBtn.setActionCommand("SUBMIT");
        rcsubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rcrcsubmitBtnActionPerformed(evt);
            }
        });
        jPanel1.add(rcsubmitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 560, 100, 20));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("REPORT CRIME HERE");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 290, 300, 31));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/NUPDnobg.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/POLICE2.jpeg"))); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1480, 910));

        jTabbedPane1.addTab("Report Crime", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        detailsTable.setBackground(new java.awt.Color(0, 0, 51));
        detailsTable.setForeground(new java.awt.Color(255, 255, 255));
        detailsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Phone", "Address", "Crime Details", "Officer Name", "Action Taken"
            }
        ));
        jScrollPane1.setViewportView(detailsTable);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 750, 350));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setText("CRIME DETAILS");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 150, -1, 32));

        viewBtn.setBackground(new java.awt.Color(0, 0, 0));
        viewBtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        viewBtn.setForeground(new java.awt.Color(255, 255, 255));
        viewBtn.setText("VIEW");
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });
        jPanel2.add(viewBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 580, 80, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/POLICE2.jpeg"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTabbedPane1.addTab("Crime Details", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnStudLogout1.setBackground(new java.awt.Color(0, 0, 0));
        btnStudLogout1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnStudLogout1.setForeground(new java.awt.Color(255, 255, 255));
        btnStudLogout1.setText("LOGOUT");
        btnStudLogout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudLogout1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnStudLogout1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 410, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel10.setText("End Current Session?");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 360, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/NUPD-login logo.png"))); // NOI18N
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 160, -1, 180));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/POLICE2.jpeg"))); // NOI18N
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1480, 980));

        jTabbedPane1.addTab("Action", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rcrcnameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rcrcnameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rcrcnameTxtActionPerformed

    private void rcrcphoneTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rcrcphoneTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rcrcphoneTxtActionPerformed
    String currName = "";
    String currentRole = "";
    public void getUserData(String user, String role){
        rcnameTxt.setText(user);
        currName = user;
        currentRole = role;
    }
    
//    public class CrimeReport{
//        
//        
//        public static void CreateCrimeReport(String name, int phone, String address, String cd){
//            
//             try{
//            java.sql.Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/universitysystem", "root", "user@1234");
//            
//            System.out.println("connection open");
//            java.sql.Statement statement = connection.createStatement();
//                        System.out.println("connection open");
//
//            String query = "INSERT INTO universitysystem.crimeReport (name,phone,address,crimeDetails) values(?,?,?,?)";
//                        System.out.println("connection insert");
//
//           // java.sql.PreparedStatement preparedStmt = connection.prepareStatement(query);
//            java.sql.PreparedStatement preparedStmt = connection.prepareStatement(query);
//            preparedStmt.setString(1,name);
//            
//            System.out.println("connection insert");
//            
//            preparedStmt.setInt(2,phone);
//            preparedStmt.setString(3,address);
//            preparedStmt.setString(4,cd);
//
//
//            System.out.println("connection insert");
//
//            preparedStmt.execute();
//             System.out.println("connection run");
//             JOptionPane.showMessageDialog(null,"Details Added");
//
//             connection.close();
//        }
//        catch(Exception e){
//            System.out.println(e);
//            JOptionPane.showMessageDialog(null,"please add data in correct format!");
//        }      
//             
//        }
//    
//    } 
    
    
    
    private void rcrcsubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rcrcsubmitBtnActionPerformed
        // TODO add your handling code here:
        String name = rcnameTxt.getText();
        int phone = Integer.parseInt(rcphoneTxt.getText());
        String address = rcaddressTxt.getText();
        String cd = rccdTxt.getText();

        
       
       
        
        if(rcaddressTxt.getText().isEmpty()|| rcnameTxt.getText().isEmpty()||rcphoneTxt.getText().isEmpty()||rccdTxt.getText().isEmpty()           ){
                 JOptionPane.showMessageDialog(null, "Plz Enter Details!");

        
        } else{

        
        // Community.CreateCommunity(house,person,community,city,hospital);
         //CrimeReport.CreateCrimeReport(name,phone,address,cd);
         crimereport report =  new crimereport(name,phone,address,cd);
               report.addCrime();
        }
    }//GEN-LAST:event_rcrcsubmitBtnActionPerformed

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tb1Model = (DefaultTableModel)detailsTable.getModel();
        tb1Model.setRowCount(0);
        try{
            java.sql.Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/universitysystem", "root", "Masters@23");
            java.sql.Statement statement = connection.createStatement();
            String studentQuery = "SELECT * FROM universitysystem.crimedetails WHERE Name = '"+currName+"'";
            java.sql.ResultSet studentData = statement.executeQuery(studentQuery);

            while(studentData.next()){
                String  name = studentData.getString("name");
                String phone = studentData.getString("phone");
                String address = studentData.getString("address");
                String crimeDetails = studentData.getString("crimeDetails");
                String officer = studentData.getString("officer");
                String action = studentData.getString("action");


                
                String tbData[] = {name, phone,address,crimeDetails,officer,action};
                
                tb1Model.addRow(tbData);
            }
            
         }catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getLocalizedMessage());
         }   
    }//GEN-LAST:event_viewBtnActionPerformed

    private void btnStudLogout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudLogout1ActionPerformed
        // TODO add your handling code here:
        emergencyLogin emergencyLoginObj = new emergencyLogin();
        setVisible(false);
        emergencyLoginObj.setVisible(true);
    }//GEN-LAST:event_btnStudLogout1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(crimeReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(crimeReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(crimeReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(crimeReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new crimeReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStudLogout1;
    private javax.swing.JTable detailsTable;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel rcaddress;
    private javax.swing.JTextField rcaddressTxt;
    private javax.swing.JTextField rccdTxt;
    private javax.swing.JLabel rccrimedetails;
    private javax.swing.JLabel rcname;
    private javax.swing.JTextField rcnameTxt;
    private javax.swing.JLabel rcphone;
    private javax.swing.JTextField rcphoneTxt;
    private javax.swing.JButton rcsubmitBtn;
    private javax.swing.JButton viewBtn;
    // End of variables declaration//GEN-END:variables
}
