/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package emergencyEnterprise;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.mysql.cj.jdbc.result.ResultSetMetaData;
import com.sun.jdi.connect.spi.Connection;
import emergencyEnterprise.emergency.Model.Police;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Team NYAM
 */
public class policeAdmin extends javax.swing.JFrame {

    /**
     * Creates new form policeAdmin
     */
    public policeAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        detailsTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        searchTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        policeTableD = new javax.swing.JTable();
        viewDBtn = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        employeeTable = new javax.swing.JTable();
        viewBEBtn = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        studentTable = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        professorTable = new javax.swing.JTable();
        viewSBtn = new javax.swing.JButton();
        viewPBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnStudLogout = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        policeTable = new javax.swing.JTable();
        designationTxt = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        updateBtn = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        ageTxt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        genderTxt = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        phoneTxt = new javax.swing.JTextField();
        addTxt = new javax.swing.JButton();
        salaryTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        usernameTxt = new javax.swing.JTextField();
        passwordTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        viewBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        jLabellogoaddpolice = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(128, 185, 229));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        detailsTable.setBackground(new java.awt.Color(0, 0, 51));
        detailsTable.setForeground(new java.awt.Color(255, 255, 255));
        detailsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Phone", "Address", "Crime Details", "Officer Name", "Action Taken"
            }
        ));
        jScrollPane2.setViewportView(detailsTable);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 652, 294));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setText("CRIME DETAILS");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, 200, 32));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("VIEW");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 650, 100, 30));

        searchTxt.setForeground(new java.awt.Color(153, 0, 0));
        searchTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchTxtKeyPressed(evt);
            }
        });
        jPanel2.add(searchTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 290, 217, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("SEARCH:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 70, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/NUPDnobg.png"))); // NOI18N
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 90, 90));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/POLICE2.jpeg"))); // NOI18N
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1490, 1030));

        jTabbedPane1.addTab("Complaint Records", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        policeTableD.setBackground(new java.awt.Color(0, 0, 51));
        policeTableD.setForeground(new java.awt.Color(255, 255, 255));
        policeTableD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Gender", "Age", "Phone", "Salary", "Designation"
            }
        ));
        policeTableD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                policeTableDMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(policeTableD);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 460, 170));

        viewDBtn.setBackground(new java.awt.Color(0, 0, 0));
        viewDBtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        viewDBtn.setForeground(new java.awt.Color(255, 255, 255));
        viewDBtn.setText("VIEW");
        viewDBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDBtnActionPerformed(evt);
            }
        });
        jPanel3.add(viewDBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, -1, -1));

        employeeTable.setBackground(new java.awt.Color(0, 0, 51));
        employeeTable.setForeground(new java.awt.Color(255, 255, 255));
        employeeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Gender", "Age", "Phone"
            }
        ));
        jScrollPane4.setViewportView(employeeTable);

        jPanel3.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 160, 440, 160));

        viewBEBtn.setBackground(new java.awt.Color(0, 0, 0));
        viewBEBtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        viewBEBtn.setForeground(new java.awt.Color(255, 255, 255));
        viewBEBtn.setText("VIEW");
        viewBEBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBEBtnActionPerformed(evt);
            }
        });
        jPanel3.add(viewBEBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 330, -1, -1));

        studentTable.setBackground(new java.awt.Color(0, 0, 51));
        studentTable.setForeground(new java.awt.Color(255, 255, 255));
        studentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Email", "Age"
            }
        ));
        jScrollPane5.setViewportView(studentTable);

        jPanel3.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 450, 170));

        professorTable.setBackground(new java.awt.Color(0, 0, 51));
        professorTable.setForeground(new java.awt.Color(255, 255, 255));
        professorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Email", "Age"
            }
        ));
        jScrollPane6.setViewportView(professorTable);

        jPanel3.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 430, 470, 170));

        viewSBtn.setBackground(new java.awt.Color(0, 0, 0));
        viewSBtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        viewSBtn.setForeground(new java.awt.Color(255, 255, 255));
        viewSBtn.setText("VIEW");
        viewSBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSBtnActionPerformed(evt);
            }
        });
        jPanel3.add(viewSBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 610, -1, -1));

        viewPBtn.setBackground(new java.awt.Color(0, 0, 0));
        viewPBtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        viewPBtn.setForeground(new java.awt.Color(255, 255, 255));
        viewPBtn.setText("VIEW");
        viewPBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPBtnActionPerformed(evt);
            }
        });
        jPanel3.add(viewPBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 610, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("POLICE");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("BANK EMPLOYEE");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 130, -1, 16));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("PROFESSOR");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 400, -1, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("STUDENT");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, -1, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/POLICE2.jpeg"))); // NOI18N
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -70, 1490, 1130));

        jTabbedPane1.addTab("Documentation", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        btnStudLogout.setBackground(new java.awt.Color(0, 0, 0));
        btnStudLogout.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnStudLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnStudLogout.setText("LOGOUT");
        btnStudLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudLogoutActionPerformed(evt);
            }
        });
        jPanel4.add(btnStudLogout);
        btnStudLogout.setBounds(640, 430, 110, 30);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/NUPD-login logo.png"))); // NOI18N
        jPanel4.add(jLabel19);
        jLabel19.setBounds(630, 190, 140, 200);

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel21.setText("End Current Session?");
        jPanel4.add(jLabel21);
        jLabel21.setBounds(580, 370, 230, 50);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/POLICE2.jpeg"))); // NOI18N
        jPanel4.add(jLabel20);
        jLabel20.setBounds(-60, -50, 1540, 1030);

        jTabbedPane1.addTab("Action", jPanel4);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        policeTable.setBackground(new java.awt.Color(0, 0, 51));
        policeTable.setForeground(new java.awt.Color(255, 255, 255));
        policeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Gender", "Phone", "Age", "Salary", "Designation"
            }
        ));
        policeTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                policeTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(policeTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 830, 270));

        designationTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Major ", "Sergeant", "CBI", "Officer" }));
        jPanel1.add(designationTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 190, 150, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("GENDER:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, 70, 17));

        updateBtn.setBackground(new java.awt.Color(0, 0, 0));
        updateBtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateBtn.setText("UPDATE");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        jPanel1.add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 650, 90, 23));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setText("NAME:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 60, 20));
        jPanel1.add(ageTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, 150, -1));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel15.setText("PHONE:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 60, 17));
        jPanel1.add(nameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, 150, -1));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel16.setText("AGE:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, 40, 17));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel17.setText("SALARY:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 310, 70, 17));

        genderTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jPanel1.add(genderTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 230, 150, -1));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel18.setText("DESIGNATION:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 190, -1, 17));
        jPanel1.add(phoneTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, 150, -1));

        addTxt.setBackground(new java.awt.Color(0, 0, 0));
        addTxt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        addTxt.setForeground(new java.awt.Color(255, 255, 255));
        addTxt.setText("ADD");
        addTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTxtActionPerformed(evt);
            }
        });
        jPanel1.add(addTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 650, 80, 23));
        jPanel1.add(salaryTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 310, 150, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADD POLICE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 100, 270, 40));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("USERNAME:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 230, 100, 17));
        jPanel1.add(usernameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 230, 151, -1));
        jPanel1.add(passwordTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 270, 151, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("PASSWORD:");
        jLabel7.setToolTipText("");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 270, 90, 17));

        viewBtn.setBackground(new java.awt.Color(0, 0, 0));
        viewBtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        viewBtn.setForeground(new java.awt.Color(255, 255, 255));
        viewBtn.setText("REFRESH");
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });
        jPanel1.add(viewBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 650, -1, 23));

        deleteBtn.setBackground(new java.awt.Color(0, 0, 0));
        deleteBtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setText("DELETE");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        jPanel1.add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 650, -1, 23));

        jLabellogoaddpolice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/NUPDnobg.png"))); // NOI18N
        jPanel1.add(jLabellogoaddpolice, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/POLICE2.jpeg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1520, 1050));

        jTabbedPane1.addTab("Add Police", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String policeUsername = "";
    private void policeTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_policeTableMouseClicked
        // TODO add your handling code here:
        DefaultTableModel profModel = (DefaultTableModel)policeTable.getModel();
        String PnameTxt = policeTable.getValueAt(policeTable.getSelectedRow(), 0).toString();
        nameTxt.setText(policeTable.getValueAt(policeTable.getSelectedRow(), 0).toString());        
        genderTxt.setSelectedItem(policeTable.getValueAt(policeTable.getSelectedRow(), 1).toString());
        ageTxt.setText(policeTable.getValueAt(policeTable.getSelectedRow(), 3).toString());
        phoneTxt.setText(policeTable.getValueAt(policeTable.getSelectedRow(), 2).toString());
        salaryTxt.setText(policeTable.getValueAt(policeTable.getSelectedRow(), 4).toString());
        designationTxt.setSelectedItem(policeTable.getValueAt(policeTable.getSelectedRow(), 5).toString());
System.out.println(PnameTxt);


        try{
            java.sql.Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/universitysystem", "root", "Masters@23");
            java.sql.Statement statement = connection.createStatement();
            String profQuery = "SELECT * FROM universitysystem.police WHERE name = '"+PnameTxt+"'";
            java.sql.ResultSet profData = statement.executeQuery(profQuery);
            while(profData.next()){
                policeUsername = profData.getString("username");
                System.out.println(policeUsername);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
         }

    }//GEN-LAST:event_policeTableMouseClicked

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        DefaultTableModel profModel = (DefaultTableModel)policeTable.getModel();

        String Name = nameTxt.getText();
        String Gender = (String) genderTxt.getSelectedItem();

        int age = Integer.parseInt(ageTxt.getText());
        int phone = Integer.parseInt(phoneTxt.getText());
        int salary = Integer.parseInt(salaryTxt.getText());
        String Designation = (String) designationTxt.getSelectedItem();


        if(policeUsername.isEmpty()){
            JOptionPane.showMessageDialog(null,"Professor name is empty");
        }else{
            try{
                java.sql.Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/universitysystem", "root", "Masters@23");
                java.sql.Statement statement = connection.createStatement();
            String profQuery = "UPDATE universitysystem.police SET name = '"+Name+"', gender = '"+Gender+"', age = '"+age+"', phone = '"+phone+"',phone = '"+phone+"',phone = '"+phone+"' WHERE username = '"+policeUsername+"'";
            statement.executeUpdate(profQuery);
                JOptionPane.showMessageDialog(null,"Updated successfully");
            }catch(Exception e){
                             JOptionPane.showMessageDialog(null,e);

            }
            
}
    }//GEN-LAST:event_updateBtnActionPerformed

    
    
    
    
    private void addTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTxtActionPerformed
        // TODO add your handling code here:

        String name = nameTxt.getText();
        String gender = genderTxt.getSelectedItem().toString();
        //int age = ageTxt.getText();
        int age = Integer.parseInt(ageTxt.getText());
        int phone = Integer.parseInt(phoneTxt.getText());
        String username = usernameTxt.getText();
        String password = passwordTxt.getText();


        int salary = Integer.parseInt(salaryTxt.getText());
        String designation =  (String) designationTxt.getSelectedItem();

        if(usernameTxt.getText().isEmpty()|| nameTxt.getText().isEmpty()||ageTxt.getText().isEmpty()||salaryTxt.getText().isEmpty()           ){
            JOptionPane.showMessageDialog(null, "Plz Enter Details!");

        } else{

            // Community.CreateCommunity(house,person,community,city,hospital);
            //Police.CreatePolice(id,name,gender,age,phone,salary,designation,username,password);
             
               Police police =  new Police(name,gender,age,phone,username,password,salary,designation);
               police.addPolice();

             
             
        }

        //JOptionPane.showMessageDialog(this,"New Employ details Added");

        genderTxt.setSelectedItem("");
        nameTxt.setText("");
        ageTxt.setText("");
        phoneTxt.setText("");
        salaryTxt.setText("");
        designationTxt.setSelectedItem("");
        usernameTxt.setText("");
        passwordTxt.setText("");


       // police_table();
    }//GEN-LAST:event_addTxtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         DefaultTableModel tb1Model = (DefaultTableModel)detailsTable.getModel();
        tb1Model.setRowCount(0);
        try{
            java.sql.Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/universitysystem", "root", "Masters@23");
            java.sql.Statement statement = connection.createStatement();
            String studentQuery = "SELECT * FROM universitysystem.crimedetails";
            java.sql.ResultSet studentData = statement.executeQuery(studentQuery);

            while(studentData.next()){
                String  name = studentData.getString("name");
                String phone = studentData.getString("phone");
                String address = studentData.getString("address");
                String crimeDetails = studentData.getString("crimeDetails");
                String officer = studentData.getString("officer");
                String action = studentData.getString("action");


                
                String tbData[] = {name, phone,address,crimeDetails,officer,action};
                
                tb1Model.addRow(tbData);
            }
            
         }catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getLocalizedMessage());
         }   
    }//GEN-LAST:event_jButton1ActionPerformed

    private void searchTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchTxtKeyPressed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)detailsTable.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        detailsTable.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(searchTxt.getText().trim()));
    }//GEN-LAST:event_searchTxtKeyPressed

    private void policeTableDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_policeTableDMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_policeTableDMouseClicked

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        // TODO add your handling code here:
          DefaultTableModel tb1Model = (DefaultTableModel)policeTable.getModel();
        tb1Model.setRowCount(0);
        try{
            java.sql.Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/universitysystem", "root", "Masters@23");
            java.sql.Statement statement = connection.createStatement();
            String studentQuery = "SELECT * FROM universitysystem.police";
            java.sql.ResultSet studentData = statement.executeQuery(studentQuery);

            while(studentData.next()){
                String  name = studentData.getString("name");
                String gender = studentData.getString("gender");
                String phone = studentData.getString("phone");
                String age = studentData.getString("age");
                String salary = studentData.getString("salary");
                String designation = studentData.getString("designation");

                
                String tbData[] = {name, gender, phone,age,salary,designation};
                
                tb1Model.addRow(tbData);
            }
            
         }catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getLocalizedMessage());
         }
    }//GEN-LAST:event_viewBtnActionPerformed

    private void viewBEBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBEBtnActionPerformed
        // TODO add your handling code here:
           DefaultTableModel tb1Model = (DefaultTableModel)employeeTable.getModel();
        tb1Model.setRowCount(0);
        try{
            java.sql.Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/universitysystem", "root", "Masters@23");
            java.sql.Statement statement = connection.createStatement();
            String studentQuery = "SELECT * FROM universitysystem.bankemployee";
            java.sql.ResultSet studentData = statement.executeQuery(studentQuery);

            while(studentData.next()){
                //String id = studentData.getString("Id");
                String  name = studentData.getString("Name");
                String gender = studentData.getString("Gender");
                String phone = studentData.getString("Phone");
                String age = studentData.getString("Age");
               // String salary = studentData.getString("Salary");
               // String accountType = studentData.getString("AccountType");

                
                String tbData[] = {name, gender, phone,age};
                
                tb1Model.addRow(tbData);
            }
            
         }catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getLocalizedMessage());
         }
    }//GEN-LAST:event_viewBEBtnActionPerformed

    private void viewDBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDBtnActionPerformed
        // TODO add your handling code here:
          DefaultTableModel tb1Model = (DefaultTableModel)policeTableD.getModel();
        tb1Model.setRowCount(0);
        try{
            java.sql.Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/universitysystem", "root", "Masters@23");
            java.sql.Statement statement = connection.createStatement();
            String studentQuery = "SELECT * FROM universitysystem.police";
            java.sql.ResultSet studentData = statement.executeQuery(studentQuery);

            while(studentData.next()){
                String  name = studentData.getString("name");
                String gender = studentData.getString("gender");
                String phone = studentData.getString("phone");
                String age = studentData.getString("age");
                String salary = studentData.getString("salary");
                String designation = studentData.getString("designation");

                
                String tbData[] = {name, gender, phone,age,salary,designation};
                
                tb1Model.addRow(tbData);
            }
            
         }catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getLocalizedMessage());
         }
    }//GEN-LAST:event_viewDBtnActionPerformed

    private void viewSBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSBtnActionPerformed
        // TODO add your handling code here:
         DefaultTableModel tb1Model = (DefaultTableModel)studentTable.getModel();
        tb1Model.setRowCount(0);
        try{
            java.sql.Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/universitysystem", "root", "Masters@23");
            java.sql.Statement statement = connection.createStatement();
            String studentQuery = "SELECT * FROM universitysystem.students";
            java.sql.ResultSet studentData = statement.executeQuery(studentQuery);

            while(studentData.next()){
                String  name = studentData.getString("Name");
                String email = studentData.getString("Email");

                String age = studentData.getString("Age");

                
                String tbData[] = {name,email,age};
                
                tb1Model.addRow(tbData);
            }
            
         }catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getLocalizedMessage());
         }
    }//GEN-LAST:event_viewSBtnActionPerformed

    private void viewPBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPBtnActionPerformed
        // TODO add your handling code here:
         DefaultTableModel tb1Model = (DefaultTableModel)professorTable.getModel();
        tb1Model.setRowCount(0);
        try{
            java.sql.Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/universitysystem", "root", "Masters@23");
            java.sql.Statement statement = connection.createStatement();
            String studentQuery = "SELECT * FROM universitysystem.professors";
            java.sql.ResultSet studentData = statement.executeQuery(studentQuery);

            while(studentData.next()){
                String  name = studentData.getString("Name");
                String email = studentData.getString("Email");

                String age = studentData.getString("Age");

                
                String tbData[] = {name,email,age};
                
                tb1Model.addRow(tbData);
            }
            
         }catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getLocalizedMessage());
         }
        
    }//GEN-LAST:event_viewPBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
         try{
            java.sql.Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/universitysystem", "root", "Masters@23");
            java.sql.Statement statement = connection.createStatement();
                
            statement.executeUpdate("DELETE FROM universitysystem.police WHERE username = '"+policeUsername+"'");
            JOptionPane.showMessageDialog(null, "Police Deleted !");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
        nameTxt.setText("");
        phoneTxt.setText("");
        ageTxt.setText("");
        salaryTxt.setText("");
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void btnStudLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudLogoutActionPerformed
        // TODO add your handling code here:
        emergencyLogin emergencyLoginObj = new emergencyLogin();
        setVisible(false);
        emergencyLoginObj.setVisible(true);
    }//GEN-LAST:event_btnStudLogoutActionPerformed

    
    public void police_table(){
        try{
            java.sql.Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/universitysystem", "root", "Masters@23");
            
            System.out.println("connection open");
            java.sql.Statement statement = connection.createStatement();
            String sql = "SELECT * FROM universitysystem.police;";
           // statement.executeUpdate("insert into hospitalsystem.login" + "(role, username, password)" + "values ('"+role+"','"+username+"', '"+password+"')");
            //JOptionPane.showMessageDialog(null, "User successfully added!");
            java.sql.ResultSet rs = statement.executeQuery(sql);
            while(rs.next()){
                String id = rs.getString("id");
                String name = rs.getString("name");
                String gender = rs.getString("gender");
                String age = rs.getString("age");
                String phone = rs.getString("phone");
                String salary = rs.getString("salary");
                String designation = rs.getString("designation");

                
                
                String tbData[] = {id,name,gender,age,phone,salary,designation};
                DefaultTableModel tb1Model = (DefaultTableModel)policeTable.getModel();
                
                tb1Model.addRow(tbData);
                 System.out.println("Ashish well done");
                
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"please add data in correct format!");
    }                                 
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(policeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(policeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(policeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(policeAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new policeAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addTxt;
    private javax.swing.JTextField ageTxt;
    private javax.swing.JButton btnStudLogout;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JComboBox<String> designationTxt;
    private javax.swing.JTable detailsTable;
    private javax.swing.JTable employeeTable;
    private javax.swing.JComboBox<String> genderTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabellogoaddpolice;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JTextField passwordTxt;
    private javax.swing.JTextField phoneTxt;
    private javax.swing.JTable policeTable;
    private javax.swing.JTable policeTableD;
    private javax.swing.JTable professorTable;
    private javax.swing.JTextField salaryTxt;
    private javax.swing.JTextField searchTxt;
    private javax.swing.JTable studentTable;
    private javax.swing.JButton updateBtn;
    private javax.swing.JTextField usernameTxt;
    private javax.swing.JButton viewBEBtn;
    private javax.swing.JButton viewBtn;
    private javax.swing.JButton viewDBtn;
    private javax.swing.JButton viewPBtn;
    private javax.swing.JButton viewSBtn;
    // End of variables declaration//GEN-END:variables
}
